import type { Metadata } from "next";
import { Lato, Playfair_Display } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import Footer from "@/components/Footer";
import NavBar from "@/components/NavBar";

const beautiful = localFont({
	src: "../fonts/beautiful.woff2",
	variable: "--font-beautiful",
});
const lato = Lato({
	subsets: ["latin"],
	weight: ["400", "700"],
	variable: "--font-lato",
	display: "swap",
});

const playfair = Playfair_Display({
	subsets: ["latin"],
	weight: ["400", "700"],
	variable: "--font-playfair",
	display: "swap",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			lang="fr"
			className={`${beautiful.variable}  ${lato.variable} ${playfair.variable} antialiased`}
		>
			<NavBar />
			<body className="bg-themewhite">{children}</body>
			<Footer />
		</html>
	);
}
